pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = "GTNH Maven"
            url = "https://nexus.gtnewhorizons.com/repository/public/"
        }
        maven {
            name = "Forge"
            url = "https://maven.minecraftforge.net/"
        }
    }
}

rootProject.name = 'StoragePlus'

includeBuild('forge/1.7.9')
includeBuild('forge/1.12.2')
includeBuild('forge/1.16.5')
